# Generated by Django 6.0.1 on 2026-01-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_system_id', models.IntegerField()),
                ('home_system_name', models.CharField(max_length=255)),
                ('allowed_jumps', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='MovementAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255)),
                ('ship_type_name', models.CharField(max_length=255)),
                ('old_system', models.CharField(max_length=255)),
                ('new_system', models.CharField(max_length=255)),
                ('distance_from_home', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField()),
                ('character_name', models.CharField(max_length=255)),
                ('ship_type_id', models.IntegerField()),
                ('ship_type_name', models.CharField(max_length=255)),
                ('system_id', models.IntegerField(blank=True, null=True)),
                ('system_name', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_from_home', models.IntegerField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
