# Generated by Django 5.2.10 on 2026-01-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveuniverse', '0011_extend_industry_activites'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapTrackSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blacklisted_regions', models.ManyToManyField(blank=True, help_text='Select regions to blacklist for capital tracking.', to='eveuniverse.everegion')),
            ],
            options={
                'verbose_name': 'CapTrack settings',
                'verbose_name_plural': 'CapTrack settings',
            },
        ),
    ]
