# Generated by Django 6.0.1 on 2026-01-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveuniverse', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapTrackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted_regions', models.ManyToManyField(blank=True, help_text='Select regions to blacklist for capital tracking.', to='eveuniverse.everegion')),
            ],
            options={
                'verbose_name': 'CapTrack settings',
                'verbose_name_plural': 'CapTrack settings',
            },
        ),
    ]
