# Generated by Django 4.2.27 on 2026-01-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captracksettings',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Discord webhook URL for cap notifications.', null=True),
        ),
    ]
