# Generated by Django 4.2.27 on 2026-01-10 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('captrack', '0002_captracksettings_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapAlertCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('last_alert', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
