# Generated by Django 4.2.27 on 2026-01-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captrack', '0006_captrack_admin_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapAlertCooldown',
        ),
        migrations.AlterField(
            model_name='captracksettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='captracksettingsaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='CapWatchlist',
        ),
    ]
