# Generated by Django 4.2.27 on 2026-01-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captrack', '0006b_create_captracksettingsaudit'),
        ('captrack', '0007_delete_capalertcooldown_alter_captracksettings_id_and_more'),
    ]

    operations = [
    ]
