# Generated by Django 5.2.12 on 2026-03-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captrack', '0007_swap_blacklisted_regions_to_sde'),
        ('eve_sde', '0018_blueprintactivity_blueprintactivityproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captracksettings',
            name='blacklisted_regions',
            field=models.ManyToManyField(blank=True, help_text='Select regions to blacklist for capital tracking.', to='eve_sde.region'),
        ),
    ]
