# Generated by Django 5.2.12 on 2026-03-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captrack', '0006_swap_blacklisted_regions_to_sde'),
        ('captrack', '0008_alter_captracksettings_blacklisted_regions'),
    ]

    operations = [
    ]
